name: Schedule Build Docker Images For Main Images And Nightly

on:
  schedule:
    - cron: '0 0 * * *'

jobs:

  build_and_publish_images:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        image_type: [ latest,
                      alpine,
                      postgres_12,
                      nightly ]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Clone tools branch
        run: git clone --depth=1 --branch update_properties_fixes https://github.com/citusdata/tools.git tools

      - name: Install package dependencies
        run: sudo apt install libcurl4-openssl-dev libssl-dev

      - name: Install python requirements
        run: python -m pip install -r tools/packaging_automation/requirements.txt

      - name: Build and publish docker images
        run: |
          python -m  tools.packaging_automation.publish_docker  --pipeline_trigger_type "${GITHUB_EVENT_NAME}"\
           --exec_path "$(pwd)" --image_type ${{ matrix.image_type }}
